version: '3'
services:

  docker-mysql-db:
    image: mysql:latest
    container_name: docker-mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=calculatordb
    expose:
      - "3306"

  user-front-api:
    image: user-front-api:latest
    container_name: user-front-api
    ports:
      - 8081:8081

  backend-calculator-api:
    image: backend-calculator-api:latest
    container_name: backend-calculator-api
    depends_on:
      - docker-mysql-db
    ports:
      - 8082:8082
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql-db:3306/calculatordb?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_PLATFORM=org.hibernate.dialect.MySQL5Dialect